### ISSUE TITLE
Button Mushroom Grower Not Visible in Web Client

### ISSUE THREAD

**Issue by AntumDeluge** [arianne/stendhal#349]
## 🐞 Describe the bug

The web client is looking for the wrong image to display the button mushroom grower. It is looking for "button mushroom_grower.png" instead of "button_mushroom_grower.png":

Server log output:
```
2020-02-24 04:29:28.343:WARN:oejs.ServletHandler:qtp614785733-32: /data/sprites/items/grower/button%20mushroom_grower.png
java.io.FileNotFoundException: /data/sprites/items/grower/button mushroom_grower.png
	at marauroa.server.net.web.WebServletForStaticContent.sendFile(WebServletForStaticContent.java:129)
	at marauroa.server.net.web.WebServletForStaticContent.doGet(WebServletForStaticContent.java:67)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:748)
```

Other growers with whitespace in the name seem to be working. I checked the "iron ore" grower.

## 🔥 How to reproduce

Visit any map where a button mushroom grower is.

## 🌍  Environment

- Web client

**Comment by AntumDeluge** [comment]
Closing, but I believe there is still an underlying issue with the string "button".
