### ISSUE TITLE
GrocerNPC.lua:26 attempt to call nil

### ISSUE THREAD

**Issue by nhnb** [arianne/stendhal#351]
## 🐞 Describe the bug

A clear description of the issue.

## 🔥 How to reproduce

Start the main game server. No error on test server.

## 🌍  Environment

Server

## 🔭 Additional information

~~~~
 Error while loading region/deniran/city/interior/grocery_store/GrocerNPC.lua:
org.luaj.vm2.LuaError: @data/script/region/deniran/city/interior/grocery_store/GrocerNPC.lua:26 attempt to call nil
        at org.luaj.vm2.LuaValue.checkmetatag(Unknown Source)
        at org.luaj.vm2.LuaValue.callmt(Unknown Source)
        at org.luaj.vm2.LuaValue.call(Unknown Source)
        at org.luaj.vm2.LuaClosure.execute(Unknown Source)
        at org.luaj.vm2.LuaClosure.call(Unknown Source)
        at org.luaj.vm2.LuaClosure.execute(Unknown Source)
        at org.luaj.vm2.LuaClosure.call(Unknown Source)
        at games.stendhal.server.core.scripting.ScriptInLua.load(ScriptInLua.java:80)
        at games.stendhal.server.core.scripting.ScriptRunner.perform(ScriptRunner.java:200)
        at games.stendhal.server.core.scripting.ScriptRunner.perform(ScriptRunner.java:116)
        at games.stendhal.server.core.scripting.ScriptRunner.perform(ScriptRunner.java:112)
        at games.stendhal.server.core.scripting.ScriptRunner.init(ScriptRunner.java:101)
        at games.stendhal.server.core.engine.StendhalRPRuleProcessor.setContext(StendhalRPRuleProcessor.java:160)
        at marauroa.server.game.rp.RPServerManager.initializeExtensions(RPServerManager.java:179)
        at marauroa.server.game.rp.RPServerManager.<init>(RPServerManager.java:138)
        at marauroa.server.marauroad.init(marauroad.java:355)
        at marauroa.server.marauroad.main(marauroad.java:199)
~~~~

**Comment by AntumDeluge** [comment]
This is occurring because I forgot to add 84560cc40ebfcb2e1dbbf8dcf3367e1496c178f6 to the release branch. There are some other commits that the grocer requires as well: fa03726510a6a3fe5fb885bca8a65885e9a7faeb, 9ca064328f3d3c3edcc2e578ed30396bc6828a27, 9f8c05ea99cbd60f872bf49564d6b96fa7d60fa1, & 2ca94680a0dd83c7c1271a59fbd0b6d7857dd6d3
