### ISSUE TITLE
java client 1.34 not starting

### ISSUE THREAD

**Issue by tobiwankenobi-stendhal** [arianne/stendhal#371]
## 🐞 Describe the bug
The newly downloaded client stendhal-1.34 can't be started.

## 🔥 How to reproduce

1. Download [Stendhal-Client](https://arianne-project.org/download/stendhal.zip)
2. Run stendhal-starter.jar
3. See below for error message

## 🌍  Environment
```
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-8u252-b09-1~18.04-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)
```

## 🔭 Additional information
Error Message:
```
troll@bombadil:~/Programme/stendhal-1.34$ java -jar stendhal-starter.jar 
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NullPointerException
	at sun.security.pkcs.SignerInfo.getTimestamp(SignerInfo.java:565)
	at sun.security.util.SignatureFileVerifier.getSigners(SignatureFileVerifier.java:724)
	at sun.security.util.SignatureFileVerifier.processImpl(SignatureFileVerifier.java:295)
	at sun.security.util.SignatureFileVerifier.process(SignatureFileVerifier.java:263)
	at java.util.jar.JarVerifier.processEntry(JarVerifier.java:318)
	at java.util.jar.JarVerifier.update(JarVerifier.java:230)
	at java.util.jar.JarFile.initializeVerifier(JarFile.java:383)
	at java.util.jar.JarFile.ensureInitialization(JarFile.java:617)
	at java.util.jar.JavaUtilJarAccessImpl.ensureInitialization(JavaUtilJarAccessImpl.java:69)
	at sun.misc.URLClassPath$JarLoader$2.getManifest(URLClassPath.java:991)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:451)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)

```

**Comment by nhnb** [comment]
Thanks for the report. That seems to be related to some bug in the JDK. I removed tsa support from the signature of stendhal-starter.jar and that seems to have fixed the issue.

Since the certificate has expired anyway there should be no negative impact
