### ISSUE TITLE
Converting Outfit Code To Type Long Not Backward Compatible

### ISSUE THREAD

**Issue by AntumDeluge** [arianne/stendhal#55]
Not sure if there is anything that can be done about this, but in the code I am testing I have converted the outfit code & RPEntity "outfit" attributes to type long. When a player logs in, the integer values are replaced with long in the database. This makes the database inaccessible if the code is reverted back to integer.

This is the server output in such a scenario:
```
ERROR [mmandQueue] DBCommandQueueBackgroundThread(67  ) [DelayedEventHandlerThread: LoadAllActiveCharactersCommand [username=deluge, characters=null]] - marauroa.common.game.SyntaxException: attribute code 0 isn't defined.
marauroa.common.game.SyntaxException: attribute code 0 isn't defined.
	at marauroa.common.game.RPClass.getName(RPClass.java:707)
	at marauroa.common.game.RPClass.getName(RPClass.java:704)
	at marauroa.common.game.RPClass.getName(RPClass.java:704)
	at marauroa.common.game.RPClass.getName(RPClass.java:704)
	at marauroa.common.game.Attributes.readObject(Attributes.java:738)
	at marauroa.common.game.RPObject.readObject(RPObject.java:1250)
	at marauroa.common.net.InputSerializer.readObject(InputSerializer.java:50)
	at marauroa.server.game.db.RPObjectDAO.readRPObject(RPObjectDAO.java:133)
	at marauroa.server.game.db.CharacterDAO.loadAllCharacters(CharacterDAO.java:408)
	at marauroa.server.game.db.CharacterDAO.loadAllActiveCharacters(CharacterDAO.java:458)
	at marauroa.server.game.dbcommand.LoadAllActiveCharactersCommand.execute(LoadAllActiveCharactersCommand.java:62)
	at marauroa.server.db.command.DBCommandQueueBackgroundThread.executeDBAction(DBCommandQueueBackgroundThread.java:103)
	at marauroa.server.db.command.DBCommandQueueBackgroundThread.processCommand(DBCommandQueueBackgroundThread.java:75)
	at marauroa.server.db.command.DBCommandQueueBackgroundThread.run(DBCommandQueueBackgroundThread.java:49)
	at java.lang.Thread.run(Thread.java:748)
ERROR [dlerThread] DelayedEventHandlerThread(67  ) - java.lang.NullPointerException
java.lang.NullPointerException
	at marauroa.server.game.messagehandler.SendCharacterListHandler.handleDelayedEvent(SendCharacterListHandler.java:62)
	at marauroa.server.game.messagehandler.DelayedEventHandlerThread.run(DelayedEventHandlerThread.java:100)
```
Not sure that this is really an issue that would ever come up as I don't know why there would be any reason to revert back to integer type. But wanted to post it for awareness sake.

**Comment by nhnb** [comment]
Are we sure that the conversation from integer to long works without pulling in additional bytes from the next attribute?

**Comment by AntumDeluge** [comment]
Honestly, & it's a little embarrassing to admit, but I don't think I really understand how this works. All I really understand is that long supports a larger range of values, & when those values are added to the database, it appears that it cannot be re-accessed with an integer value.

**Comment by AntumDeluge** [comment]
In the code that I am currently testing, the only thing that I change is the data type from int to long. I don't make any other changes to the outfit system. My branch is located here: https://github.com/AntumDeluge/arianne-stendhal/tree/outfittypelong

**Comment by nhnb** [comment]
I had a look at `marauroa.common.Attributes.readObject()` now. When it reads objects from the database it boils down to:

~~~~
String key = in.readString();
Definition def = rpClass.getDefinition(DefinitionClass.ATTRIBUTE, key);
String value = def.deserialize(in);
~~~~

`Definition.deserialize()` dispatches the call to the appropriate method based on the definition the code. `readInt()` reads 4 bytes. `readLong` reads 8 bytes.

If there is code that handles a conversation from int to long, I am unable to find it.

**Comment by AntumDeluge** [comment]
This has been abandoned in favor of using a string type attribute for the new outfit ("outfit_ext") attribute.
