### ISSUE TITLE
Action Validator Throws Exception if Target is Offline

### ISSUE THREAD

**Issue by AntumDeluge** [arianne/stendhal#552]
## 🐞 Describe the bug

An error is thrown if `ActionTargetNotIgnoringSender` tries to validate an action while the target player is offline.

As a consequence, this validator cannot be used with the `/storemessage` command.

## 🔥 How to reproduce

After altering `games.stendhal.server.actions.chat.StoreMessageAction` to use said validator:

```diff
        public StoreMessageAction() {
                validation.add(new ActionAttributesExist(TARGET));
+               validation.add(new ActionTargetNotIgnoringSender(TARGET));
                validation.add(StandardActionValidations.CHAT);
        }
```

...it can be reproduced with the `/storemessage` chat command:
1. Make sure target player is offline
2. Execute `/storemessage <player> <message>`
3. See error in server log

> ERROR [verManager] CommandCenter            (164 ) Player [deluge, -1335443416] Attributes of Class(): [sourceid=9][zoneid=int_semos_townhall][text=foo][type=storemessage][target=tendai]- Cannot execute action Attributes of Class(): [sourceid=9][zoneid=int_semos_townhall][text=foo][type=storemessage][target=tendai] send by Player [deluge, -1335443416]
java.lang.NullPointerException: Cannot invoke "games.stendhal.server.entity.player.Player.getIgnore(String)" because "<local5>" is null
        at games.stendhal.server.actions.validator.ActionTargetNotIgnoringSender.validate(ActionTargetNotIgnoringSender.java:51)
        at games.stendhal.server.actions.validator.ActionValidation.validate(ActionValidation.java:49)
        at games.stendhal.server.actions.validator.ActionValidation.validateAndInformPlayer(ActionValidation.java:77)
        at games.stendhal.server.actions.chat.StoreMessageAction.onAction(StoreMessageAction.java:71)
        at games.stendhal.server.actions.CommandCenter.execute(CommandCenter.java:155)
        at games.stendhal.server.core.engine.StendhalRPRuleProcessor.execute(StendhalRPRuleProcessor.java:274)
        at marauroa.server.game.rp.RPScheduler.visit(RPScheduler.java:113)
        at marauroa.server.game.rp.RPServerManager.run(RPServerManager.java:649)

## 🛠️ Suggested fixes

Server needs a way to extract `ignore` information from player when offline.

**Comment by AntumDeluge** [comment]
Closing, invalid. Actions that need to check if an offline player is ignoring do not use this validator.
