### ISSUE TITLE
Database Tables 'stendhal.iteminfo' & 'stendhal.shopinventoryinfo' Accessed Before Updating

### ISSUE THREAD

**Issue by AntumDeluge** [arianne/stendhal#561]
## 🐞 Describe the bug

After updating source & building server, it failed to update the database with the new `iteminfo` & `shopinventoryinfo` tables.

```
ERROR [mmandQueue] DBCommandQueueBackgroundThread(67  ) [RPServerManager, LOW, 2023-10-30 15:26:09 195: DumpItemsCommand []] - java.sql.SQLSyntaxErro
rException: Table 'stendhal.iteminfo' doesn't exist
java.sql.SQLSyntaxErrorException: Table 'stendhal.iteminfo' doesn't exist
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:782)
        at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:666)
        at marauroa.server.db.adapter.AbstractDatabaseAdapter.execute(AbstractDatabaseAdapter.java:136)
        at marauroa.server.db.DBTransaction.execute(DBTransaction.java:175)
        at games.stendhal.server.core.engine.db.StendhalItemDAO.dump(StendhalItemDAO.java:241)
        at games.stendhal.server.core.engine.dbcommand.DumpItemsCommand.execute(DumpItemsCommand.java:30)
        at marauroa.server.db.command.DBCommandQueueBackgroundThread.executeDBAction(DBCommandQueueBackgroundThread.java:118)
        at marauroa.server.db.command.DBCommandQueueBackgroundThread.processCommand(DBCommandQueueBackgroundThread.java:87)
        at marauroa.server.db.command.DBCommandQueueBackgroundThread.run(DBCommandQueueBackgroundThread.java:54)
        at java.base/java.lang.Thread.run(Thread.java:833)
WARN  [mmandQueue] StendhalRPZone           (1841) [RPServerManager, LOW, 2023-10-30 15:26:09 196: DumpZonesCommand []] - no match: tutorial_island
WARN  [mmandQueue] StendhalRPZone           (1841) [RPServerManager, LOW, 2023-10-30 15:26:09 196: DumpZonesCommand []] - no match: bone_pillar
ERROR [mmandQueue] DBCommandQueueBackgroundThread(67  ) [RPServerManager, LOW, 2023-10-30 15:26:09 196: DumpShopsCommand []] - java.sql.SQLSyntaxErro
rException: Table 'stendhal.shopinventoryinfo' doesn't exist
java.sql.SQLSyntaxErrorException: Table 'stendhal.shopinventoryinfo' doesn't exist
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:782)
        at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:666)
        at marauroa.server.db.adapter.AbstractDatabaseAdapter.execute(AbstractDatabaseAdapter.java:136)
        at marauroa.server.db.DBTransaction.execute(DBTransaction.java:175)
        at games.stendhal.server.core.engine.db.StendhalShopDAO.dumpShopIventories(StendhalShopDAO.java:136)
        at games.stendhal.server.core.engine.db.StendhalShopDAO.dump(StendhalShopDAO.java:204)
        at games.stendhal.server.core.engine.dbcommand.DumpShopsCommand.execute(DumpShopsCommand.java:30)
        at marauroa.server.db.command.DBCommandQueueBackgroundThread.executeDBAction(DBCommandQueueBackgroundThread.java:118)
        at marauroa.server.db.command.DBCommandQueueBackgroundThread.processCommand(DBCommandQueueBackgroundThread.java:87)
        at marauroa.server.db.command.DBCommandQueueBackgroundThread.run(DBCommandQueueBackgroundThread.java:54)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

The following code is located in `games.stendhal.server.core.engine.StendhalPlayerDatabase`:
```java
		// 1.44 development version: infostring
		if (!transaction.doesColumnExist("iteminfo", "itemdata")) {
			transaction.execute("DROP TABLE iteminfo;", null);
			transaction.execute("DROP TABLE shopinventoryinfo;", null);
		}
```

~~Not sure if it is correct. It checks if the columns `iteminfo` & `itemdata` exist, & if not then it deletes the tables `iteminfo` & `shopinventoryinfo`.~~ _(determined that the problem is that the server attempts to access the tables before the database gets updated)_

## 🔥 How to reproduce

1. Create a server & database using source before `iteminfo` & `shopinventoryinfo` tables were introduced.
2. Update to latest source & rebuild.
3. Start server & see errors.

System info:

> OS: Windows 10 64-bit
Stendhal version: git @ ee7b4ccaad7966dbd27b93ca92d9e2df216839a9
MySQL version: 8.0.32

**Comment by AntumDeluge** [comment]
I restarted my server & the errors did not occur. I think this means that the code is trying to access the tables before the database is updated.
