### ISSUE TITLE
Kirla's Photos Don't Work on Local Server

### ISSUE THREAD

**Issue by AntumDeluge** [arianne/stendhal#563]
## 🐞 Describe the bug

Photos by Kirla do not work on my local server.

> [19:29] deluge: hi
> [19:29] Kirla: Pictures! Good Pictures! Memory Pictures! Buy Pictures!
> [19:29] deluge: picture
> [19:29] Kirla: Ohmmmmm, I see blury mist, Ohmmmmm. The picture is getting clearer, Ohmmmmm. Just a view more seconds...
> [19:29] Kirla: Do you want to buy this picture for 1000 money?
> [19:30] deluge: yes
> [19:30] Kirla: Here is your picture in a wooden frame.

Result:

![image](https://github.com/arianne/stendhal/assets/3631473/d8691595-accb-487a-b373-f21de1a4dbb0)

Server error:

```
ERROR [verManager] PhotographerNPC          (105 ) - java.lang.NullPointerException: Cannot invoke "String.getBytes(String)" because "<parameter2>" i
s null
java.lang.NullPointerException: Cannot invoke "String.getBytes(String)" because "<parameter2>" is null
        at games.stendhal.server.maps.quests.revivalweeks.PhotographerNPC.hmac(PhotographerNPC.java:78)
        at games.stendhal.server.maps.quests.revivalweeks.PhotographerNPC.generateUrl(PhotographerNPC.java:95)
        at games.stendhal.server.maps.quests.revivalweeks.PhotographerChatAction$1.onTurnReached(PhotographerChatAction.java:58)
        at games.stendhal.server.core.events.TurnNotifier.logic(TurnNotifier.java:111)
        at games.stendhal.server.core.engine.StendhalRPRuleProcessor.endTurn(StendhalRPRuleProcessor.java:394)
        at marauroa.server.game.rp.RPServerManager.run(RPServerManager.java:653)
ERROR [verManager] PhotographerNPC          (105 ) - java.lang.NullPointerException: Cannot invoke "String.getBytes(String)" because "<parameter2>" i
s null
java.lang.NullPointerException: Cannot invoke "String.getBytes(String)" because "<parameter2>" is null
        at games.stendhal.server.maps.quests.revivalweeks.PhotographerNPC.hmac(PhotographerNPC.java:78)
        at games.stendhal.server.maps.quests.revivalweeks.PhotographerNPC.generateUrl(PhotographerNPC.java:95)
        at games.stendhal.server.maps.quests.revivalweeks.PhotographerSellChatAction.fire(PhotographerSellChatAction.java:31)
        at games.stendhal.server.entity.npc.fsm.Engine.executeTransition(Engine.java:612)
        at games.stendhal.server.entity.npc.fsm.Engine.matchTransition(Engine.java:577)
        at games.stendhal.server.entity.npc.fsm.Engine.step(Engine.java:451)
        at games.stendhal.server.entity.npc.fsm.Engine.step(Engine.java:433)
        at games.stendhal.server.entity.npc.SpeakerNPC.tell(SpeakerNPC.java:819)
        at games.stendhal.server.entity.npc.SpeakerNPC.preLogic(SpeakerNPC.java:464)
        at games.stendhal.server.core.engine.StendhalRPRuleProcessor.executeNPCsPreLogic(StendhalRPRuleProcessor.java:354)
        at games.stendhal.server.core.engine.StendhalRPRuleProcessor.beginTurn(StendhalRPRuleProcessor.java:311)
        at marauroa.server.game.rp.RPServerManager.run(RPServerManager.java:674)
```

The first exception occurs when the image is created on screen. The second occurs when replying "yes" to purchase the image. Previewing the photo by looking at item from inventory does not throw an exception, but the resulting failure to display the image in dialog window is the same.

**Comment by AntumDeluge** [comment]
When using the the Java client it outputs error:

```
ERROR [Game loop] RPObjectChangeDispatcher.java ( 111) - dispatchModifyAdded failed, object is RPObject with Attributes of Class(player): [def=12][re
lease=1.44.5][hp=87][def_item=54][type=player][base_mana=0][move.continuous=][def_xp=124][outfit=0][atk=11][base_hp=110][id=74][height=1][adminlevel=
5000][karma=7.81][visibility=100][level=1][atk_xp=57][resistance=100][mana=0][x=66][name=deluge][xp=90][width=1][y=2][zoneid=0_semos_plains_n][outfit
_ext=body=0,dress=13,head=2,mouth=0,eyes=26,mask=0,hair=6,hat=0,detail=0][atk_item=6] and RPSlots [marauroa.common.game.RPSlot@697f164 named(trade) w
ith capacity(4)[]][marauroa.common.game.RPSlot@ca97244b named(spells) with capacity(9)[]][marauroa.common.game.RPSlot@821aab2c named(!ignore) with ca
pacity(1)[RPObject with Attributes of Class(): [id=5]]][marauroa.common.game.RPSlot@99835e10 named(bag) with capacity(15)[RPObject with Attributes of
 Class(item): [quantity=6022][visibility=100][x=0][width=1][subclass=gold][name=money][y=0][id=130][type=item][class=money][resistance=0][height=1],
RPObject with Attributes of Class(item): [amount=20][quantity=3][visibility=100][type=item][menu=Eat|Use][resistance=0][x=0][width=1][subclass=cheese
][name=cheese][y=0][id=131][class=food][height=1], RPObject with Attributes of Class(item): [quantity=1][visibility=100][type=item][menu=Look closely
|use][resistance=0][x=0][width=1][subclass=picture_in_wooden_frame][name=picture in wooden frame][y=0][id=132][state=1][class=furniture][height=1]]][
marauroa.common.game.RPSlot@245fcc24 named(rhand) with capacity(1)[RPObject with Attributes of Class(item): [visibility=100][x=0][width=1][subclass=c
lub][name=club][y=0][id=133][type=item][class=club][resistance=0][height=1]]][marauroa.common.game.RPSlot@f4581f27 named(lhand) with capacity(1)[RPOb
ject with Attributes of Class(item): [visibility=100][x=0][width=1][subclass=studded_shield][name=studded shield][y=0][id=134][type=item][class=shiel
d][resistance=0][height=1]]][marauroa.common.game.RPSlot@30cde0 named(head) with capacity(1)[]][marauroa.common.game.RPSlot@99070eda named(armor) wit
h capacity(1)[RPObject with Attributes of Class(item): [visibility=100][x=0][width=1][subclass=leather_armor][name=leather armor][y=0][id=135][type=i
tem][class=armor][resistance=0][height=1]]][marauroa.common.game.RPSlot@32a025 named(legs) with capacity(1)[]][marauroa.common.game.RPSlot@2fe5ae nam
ed(feet) with capacity(1)[]][marauroa.common.game.RPSlot@b4098369 named(finger) with capacity(1)[]][marauroa.common.game.RPSlot@5a5dbd0 named(cloak)
with capacity(1)[]][marauroa.common.game.RPSlot@cf72c10f named(keyring) with capacity(12)[]][marauroa.common.game.RPSlot@65e813b named(pouch) with ca
pacity(1)[]], changes is RPObject with Attributes of Class(player): [zoneid=0_semos_plains_n][id=74] and RPEvents [RPEvent examine with Attributes of
 Class(examine): [path=/data/sprites/][caption=deluge starting the adventure][title=Picture]]
java.lang.NullPointerException: Cannot invoke "java.awt.Image.getWidth(java.awt.image.ImageObserver)" because "this.image" is null
        at games.stendhal.client.gui.imageviewer.ImageViewPanel.initComponents(ImageViewPanel.java:72)
        at games.stendhal.client.gui.imageviewer.ImageViewPanel.prepareView(ImageViewPanel.java:50)
        at games.stendhal.client.gui.imageviewer.ImageViewWindow.<init>(ImageViewWindow.java:48)
        at games.stendhal.client.gui.imageviewer.RPEventImageViewer.view(RPEventImageViewer.java:71)
        at games.stendhal.client.gui.imageviewer.RPEventImageViewer.<init>(RPEventImageViewer.java:45)
        at games.stendhal.client.gui.imageviewer.RPEventImageViewer.viewImage(RPEventImageViewer.java:49)
        at games.stendhal.client.events.ExamineEvent.execute(ExamineEvent.java:30)
        at games.stendhal.client.events.EventDispatcher.dispatchEvents(EventDispatcher.java:35)
        at games.stendhal.client.GameObjects.onChangedAdded(GameObjects.java:260)
        at games.stendhal.client.RPObjectChangeDispatcher.fireChangedAdded(RPObjectChangeDispatcher.java:220)
        at games.stendhal.client.RPObjectChangeDispatcher.dispatchModifyAdded(RPObjectChangeDispatcher.java:108)
        at games.stendhal.client.StendhalPerceptionListener.onMyRPObject(StendhalPerceptionListener.java:102)
        at marauroa.client.net.PerceptionHandler.applyPerceptionMyRPObject(PerceptionHandler.java:269)
        at marauroa.client.net.PerceptionHandler.apply(PerceptionHandler.java:114)
        at games.stendhal.client.StendhalClient.onPerception(StendhalClient.java:215)
        at marauroa.client.ClientFramework.loop(ClientFramework.java:866)
        at games.stendhal.client.gui.j2DClient.gameLoop(j2DClient.java:266)
        at games.stendhal.client.gui.j2DClient.lambda$startGameLoop$0(j2DClient.java:204)
        at games.stendhal.client.GameLoop.loop(GameLoop.java:144)
        at games.stendhal.client.GameLoop.access$100(GameLoop.java:24)
        at games.stendhal.client.GameLoop$1.run(GameLoop.java:52)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by nhnb** [comment]
Thanks for the report. I fixed the PHP error.
