### ISSUE TITLE
Server Build with Ant Broken

### ISSUE THREAD

**Issue by AntumDeluge** [arianne/stendhal#594]
## 🐞 Describe the bug

After building server jar files with `ant server_build` I am unable to start server using the -jar switch in the command:

```
$ java -jar stendhal-server-1.44.5.jar
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/log4j/Logger
        at games.stendhal.server.StendhalServer.<clinit>(StendhalServer.java:34)
Caused by: java.lang.ClassNotFoundException: org.apache.log4j.Logger
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 1 more
```

It does work if I set the classpath & execute the main class directly via `java -cp ./*:./libs/* games.stendhal.server.StendhalServer`.

Note that 1.44 server package downloaded from https://stendhalgame.org/download.html does work:

```
$ java -jar stendhal-server-1.44.jar
Welcome to your own Stendhal Server.

This seems to be the very first start because we could not find a server.ini.
So there are some simple questions for you to create it...

Which database system do you want to use? "h2" is an integrated database that
works out of the box, "mysql" requires a MySQL or MariaDB server. If in doubt, say "h2" [h2]:
```

~~Not sure if it is related but the server package I build locally is 138mb compared to the downloaded 1.44 package's 27mb.~~ _(this is because recent changes bundle client data for the web client)_

## 🌍  Environment

- server

**Comment by AntumDeluge** [comment]
Removed "release-blocker" tag since runserver scripts now work. But executing with command `java -jar` is still broken.

**Comment by AntumDeluge** [comment]
The problem was missing jar files in Class-Path attribute of server jar's manifest file.
